"""add datum_type to uniqe constraint

Revision ID: 201be23f0f71
Revises: 88247700113
Create Date: 2019-07-31 00:08:10.419844

"""

# revision identifiers, used by Alembic.
revision = '201be23f0f71'
down_revision = '88247700113'



from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

from gryphon.lib.models.exchange import JSONEncodedMoneyDict
sa.JSONEncodedMoneyDict = JSONEncodedMoneyDict


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datum_indicators',
    sa.Column('unique_id', sa.Unicode(length=64), nullable=False),
    sa.Column('datum_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('datum_type', sa.Unicode(length=64), nullable=False),
    sa.Column('exchange', sa.Unicode(length=64), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('string_value', sa.Unicode(length=256), nullable=True),
    sa.Column('meta_data', sa.UnicodeText(length=2147483648), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('datum_id'),
    )

    # Indices.
    op.create_index('timestamp', 'datum_indicators', ['timestamp'])

    # Unique Constraints
    op.create_unique_constraint(
        name='di_uid',
        source='datum_indicators', 
        local_cols=['datum_type', 'timestamp', 'exchange']
        )
    ### end Alembic commands ###



def downgrade():
    op.drop_table('datum_indicators')


