"""update datum_indicators table

Revision ID: 2c23c2ee654d
Revises: 52d440d3f97b
Create Date: 2019-07-29 23:39:02.843844

"""

# revision identifiers, used by Alembic.
revision = '2c23c2ee654d'
down_revision = '52d440d3f97b'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql import DATETIME

from gryphon.lib.models.exchange import JSONEncodedMoneyDict
sa.JSONEncodedMoneyDict = JSONEncodedMoneyDict


def upgrade():
    op.drop_table('datum_indicators')

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datum_indicators',
    sa.Column('unique_id', sa.Unicode(length=64), nullable=False),
    sa.Column('datum_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('datum_type', sa.Unicode(length=256), nullable=False),
    sa.Column('exchange', sa.Unicode(length=256), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('string_value', sa.Unicode(length=256), nullable=True),
    sa.Column('meta_data', sa.UnicodeText(length=2147483648), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('datum_id'),
    sa.UniqueConstraint('timestamp', 'numeric_value', 'exchange', datum='_datum_unique')
    )

    # Indices.
    op.create_index('timestamp', 'datum_indicators', ['timestamp'])
    ### end Alembic commands ###



def downgrade():
    op.drop_table('datum_indicators')
