"""create datum_indicators table

Revision ID: 52d440d3f97b
Revises: 4ee15d6375e
Create Date: 2019-07-29 22:22:24.099691

"""

# revision identifiers, used by Alembic.
revision = '52d440d3f97b'
down_revision = '4ee15d6375e'



from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql import DATETIME

from gryphon.lib.models.exchange import JSONEncodedMoneyDict
sa.JSONEncodedMoneyDict = JSONEncodedMoneyDict

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datum_indicators',
    sa.Column('unique_id', sa.Unicode(length=64), nullable=False),
    sa.Column('datum_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('datum_type', sa.Unicode(length=256), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('string_value', sa.Unicode(length=256), nullable=True),
    sa.Column('meta_data', sa.UnicodeText(length=2147483648), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('datum_id')
    )

    # Indices.
    op.create_index('timestamp', 'datum_indicators', ['timestamp'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datum_indicators')
    ### end Alembic commands ###




